**Presented by: Reza Saadatyar (2024-2025)**<br/>
**E-mail: Reza.Saadatyar@outlook.com**

**1️⃣ CPU (Central Processing Unit) & GPU (Graphics Processing Unit)**<br/>
`CPU:`<br/>
  - Designed for general-purpose computing.
  - Optimized for sequential tasks.
  - Has a few powerful cores.
  - Excellent at handling complex logic and single-threaded applications.
  
`GPU:`<br/>
  - Designed for parallel processing.
  - Has thousands of smaller, less powerful cores.
  - GPUs offer far faster numerical computing than CPUs.
  - Optimized for tasks that can be divided into many independent calculations.
  - Excellent for tasks like matrix operations, which are common in deep learning.

Putting a tensor on GPU using `to(device)` (e.g. `some_tensor.to(device)`) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. `some_tensor = some_tensor.to(device)`  

**2️⃣ N-d Tensor**<br/> 
A tensor is a multi-dimensional array of numerical values. Tensor computation (like numpy) with strong GPU acceleration.<br/>
`0-dimensional (Scalar):` A single number, e.g., 5, 3.14, -10. A <font color='red'><b>scalar</b></font> is a single number and in tensor-speak it's a zero dimension tensor.<br/>
`1-dimensional (Vector):` A list of numbers, e.g., [1, 2, 3]. A <font color='blue'><b>vector</b></font> is a single dimension tensor but can contain many numbers.<br/>
`2-dimensional (Matrix):` A table of numbers, e.g., [[1, 2], [3, 4]]. <font color='green'><b>MATRIX</b></font>  has two dimensions.<br/>
`3-dimensional (or higher):` Like a "cube" of numbers or more complex higher-dimensional structures. These are common for representing images, videos, and more.<br/>

**🔸 Tensor datatypes**<br/>
There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types). Some are specific for CPU and some are better for GPU.<br/>
Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).<br/>
The most common type (and generally the default) is `torch.float32` or `torch.float`.<br/>

**3️⃣ Getting information from tensors**<br/>
`shape` - what shape is the tensor? (some operations require specific shape rules)<br/>
`dtype` - what datatype are the elements within the tensor stored in?<br/>
`device` - what device is the tensor stored on? (usually GPU or CPU)<br/>

**4️⃣ Math Operations**<br/>
`Addition` ⇒ *a+b* or *torh.add(a, b)*<br/>
`Substraction` ⇒ *a-b* or *torh.sub(a, b)*<br/>
`Multiplication (element-wise)` ⇒ *axb* <br/>
`Division` ⇒ *a/b* or *torh.div(a, b)*<br/>
`Matrix multiplication` ⇒ `@` in Python is the symbol for matrix multiplication. [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) or [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html)<br/>
`torch.mean & torch.std`
  
**5️⃣ Special Arrays**<br/>
`zeros`<br/>
`ones`<br/>
`empty`<br/>
`eye`<br/>
`full`<br/>
`arange`<br/>
`reshape`<br/>
`linspace`<br/>

🔸 Using [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

**6️⃣ Random Arrays**<br/>
`torch.rand:` Create a *n x m* tensor filled with random numbers from a uniform distribution on the interval [0, 1)<br/>
`torch.randn:` Create a *n x m* tensor filled with random numbers from a normal distribution with mean 0 and variance 1. <br/>
`torch.randint:` Create a *n x m* tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).<br/>

🔸 `torch.randperm(value):` Create a random permutation of integers from 0 to value.<br/>
🔸 `torch.permute(input, dims):` Permute the original tensor to rearrange the axis order.

**7️⃣ Indexing & Slicing**<br/>
`Indexing:` Use integer indices to specify the position of the element you want to retrieve (Accessing individual elements).<br/>
`Slicing:` Slicing allows you to extract a sub-part of your tensor by specifying a range of indices using the colon : operator (Extracting sub-tensors).<br/>
  - `start:end` (exclusive end)
  - `start:` (from start to end of dimension)
  - `:end` (from beginning to end of dimension)
  - `:` (all elements)
  - `start:end:step` (start to end with given step)

**8️⃣ Unsqueeze & squeeze**<br/>
The `squeeze()` method removes all singleton dimensions from a tensor. It will reduce the number of dimensions by removing the ones that have a size of 1.<br/>
The `unsqueeze()` method adds a singleton dimension at a specified position in a tensor. It will increase the number of dimensions by adding a size of 1 dimension at a specific position.<br/>

**9️⃣ PyTorch tensors & NumPy**<br/>
[`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html)  NumPy array → PyTorch tensor<br/>
[`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html)  PyTorch tensor → NumPy array.<br/>

**🔟 Array Manipulation**<br/>
`torch.stack:` Stacks tensors along a new dimension.<br/>
`torch.cat:` Concatenates tensors along an existing dimension.<br/>
`torch.split:` Dividing an tensor into multiple sub-arrays.<br/>
`torch.flatten:` Compresses a tensor into a contiguous 1D representation.<br/>
`torch.clone:` Creates a deep copy.<br/>
`torch.repeat:` Repeats the tensor along specified dimensions..<br/>
`torch.tile:` Repeats the tensor along specified dimensions. <br/>
`torch.unique:` Finding unique elements in a tensor.<br/>
`torch.sort, torch.argsort:` Returns both the sorted tensor and the indices of the sorted elements.<br/>
`torch.argmax, torch.argmin:` Finding the indices of the maximum and minimum values. For example, <font color="green"><b>torch.argmax()</b></font> and <font color="green"><b>torch.argmin()</b></font>.<br/>
`torch.where(condition, x, y), torch.argwhere (using torch.nonzero), extract(using arr[cond]):` Conditional operations. <font color="green"><b>torch.where()</b></font> returns elements based on a condition, <font color="green"><b>torch.nonzero()</b></font> returns indices of elements that satisfy a condition, and <font color="green"><b>arr[cond]</b></font> extracts elements based on a condition.<br/>

<font color='#FF000e' size="4.5" face="Arial"><b>Import modules</b></font>

In [2]:
import torch  #  torch.__version__  -> '2.5.1+cpu'
import numpy as np
import copy

<font color='#00ff0e' size="4.5" face="Arial"><b>1️⃣ CPU vs GPU</b></font>

In [2]:
# To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means
# "run this on the command line".
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
# torch.backends.mps.is_available() # Check for GPU on a Mac
torch.cuda.is_available()           # Check for GPU on Wind

False

In [4]:
# Set the device to 'cuda' (GPU) if a CUDA-compatible GPU is available, otherwise set it to 'cpu' (CPU)
# This is commonly used in PyTorch to ensure computations are performed on the GPU for faster processing when available
# device = "mps" if torch.backends.mps.is_available() else "cpu"
device = "cuda" if torch.cuda.is_available() else "cpu"  # Set device type
device_count =  torch.cuda.device_count()  # Count number of devices
print(f"{device = }, {device_count = }") 

device = 'cpu', device_count = 0


In [5]:
# Putting tensors (and models) on the GPU or CPU
tensor = torch.tensor([1, 2, 3]) # Create tensor (default on CPU)
tensor_on_gpu = tensor.to(device) # Move tensor to GPU (if available)
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()  # Moving tensors back to the CPU using .cpu().numpy()
tensor_on_gpu, tensor_back_on_cpu

(tensor([1, 2, 3]), array([1, 2, 3]))

<font color='#001240ee' size="4.5" face="Arial"><b>2️⃣ Scalar, Vector, Column vector, Matrix, & N-d Tensor</b></font>

In [6]:
# Create a 0-dimensional tensor (scalar) → A 0D tensor represents a single value, similar to a scalar in mathematics
torch.tensor(4/3)

tensor(1.3333)

In [7]:
# Create a 1-dimensional tensor (vector) → A 1D tensor is a list of values, similar to a vector in mathematics
a = torch.tensor([1, 2, 3])
print(f"{a = } --> {a.__class__ = }") # The `__class__` attribute shows the type of the object, which is `torch.Tensor`

a = tensor([1, 2, 3]) --> a.__class__ = <class 'torch.Tensor'>


In [8]:
# Create a 2-dimensional tensor (column vector) → A 2D tensor is a matrix with rows and columns
column_vector = torch.tensor([[1], [2], [3], [4]]) # A column vector with 4 rows and 1 column
print(column_vector)

tensor([[1],
        [2],
        [3],
        [4]])


In [3]:
# Create a 2-dimensional tensor (matrix) → A 2D tensor is a matrix with rows and columns
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]
)
print(matrix) # A 2D tensor with shape (3, 3), representing a 3x3 matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
# Create a 3-dimensional tensor
# A 3D tensor can be thought of as a collection of matrices (2D tensors) stacked along a third dimension
# Here, the tensor is created from a nested list structure with three levels:
# - The outer list represents the "depth" or "channels" (3 in this case).
# - The middle lists represent the rows of each matrix (2 in this case).
# - The inner lists represent the columns of each matrix (4 in this case).
tensor_3d = torch.tensor([[[1, 2, 2, 5],
                           [3, 4, 0, 8]],

                          [[5, 6, 6, 7],
                           [4, 8, 1, 2]],

                          [[1, 1, 8, 9],
                           [0, 0, 2, 3]]]
)
print(tensor_3d)

tensor([[[1, 2, 2, 5],
         [3, 4, 0, 8]],

        [[5, 6, 6, 7],
         [4, 8, 1, 2]],

        [[1, 1, 8, 9],
         [0, 0, 2, 3]]])


In [5]:
# Create a 4-dimensional tensor
# A 4D tensor can be thought of as a collection of 3D tensors stacked along a fourth dimension
# Here, the tensor is created from a nested list structure with four levels:
# - The outer list represents the "batch" dimension (1 in this case).
# - The next level represents the "depth" or "channels" (2 in this case).
# - The next level represents the rows of each matrix (2 in this case).
# - The innermost lists represent the columns of each matrix (4 in this case).
tensor_4d = torch.tensor([[[[1, 2, 5, 4],
                            [3, 4, 1, 0]],
                           
                           [[5, 6, 2, 3],
                            [7, 8, 6, 4]]]]
)

# A 4D tensor with shape (1, 2, 2, 4), representing:
# - 1 batch
# - 2 channels/depth
# - Each channel has 2 rows and 4 columns
print(tensor_4d)

tensor([[[[1, 2, 5, 4],
          [3, 4, 1, 0]],

         [[5, 6, 2, 3],
          [7, 8, 6, 4]]]])


In [3]:
# Create a tuple of tuples, where each inner tuple contains two integers
a = tuple([(1, 2), 
           (3, 4), 
           (5, 6)])
tensor_a = torch.tensor(a) # Convert the tuple of tuples into a PyTorch tensor
print(tensor_a) # The resulting tensor is a 2D tensor with shape (3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


<font color='#ff555e2' size="4.5" face="Arial"><b>3️⃣ Getting information from tensors</b></font>

In [13]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([1.0, 5.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.dtype, float_32_tensor.device

(torch.float32, device(type='cpu'))

In [49]:
# Create a 0-dimensional tensor (scalar) → A 0D tensor represents a single value, similar to a scalar in mathematics
# The tensor is explicitly set to have a data type of `torch.float64` (64-bit floating point) and is placed on the CPU
a = torch.tensor(4/3, dtype=torch.float64, device="cpu")

# - `a.shape`: The shape of the tensor (empty tuple for 0D tensors)
# - `a.ndim`: The number of dimensions (0 for a scalar)
# - `a.size()`: The size of the tensor (same as shape for 0D tensors)
print(f"{a = } --> {a.shape = }, {a.ndim = }, {a.size() = }")

# Convert the tensor to a different data type, `torch.float16` (16-bit floating point)
# This reduces the precision of the tensor but can save memory and improve performance
a_float16 = a.type(torch.float16)
# Alternatively, you can use `a.short()` to convert to a 16-bit integer, but this is not applicable here since the tensor is floating-point

a = tensor(1.3333, dtype=torch.float64) --> a.shape = torch.Size([]), a.ndim = 0, a.size() = torch.Size([])


<font color="#ff0051e2" size="4.5" face="Arial"><b>4️⃣ Math Operations</b></font>

In [101]:
# Create tensors
a = torch.tensor([[1, 2], 
                  [3, 4]])

b = torch.tensor([[5, 6], 
                  [7, 8]])

# Addition
add_result = a + b  # or torch.add(a, b)

# Subtraction
sub_result = a - b  # or torch.sub(a, b)

# Element-wise multiplication
mul_result = a * b

# Division
div_result = a / b  # or torch.div(a, b)

# Matrix multiplication
matmul_result = a @ b  # or torch.matmul(a, b) or torch.mm(a, b)

print(f"Addition:\n{add_result}")
print(f"\nSubtraction:\n{sub_result}")
print(f"\nElement-wise Multiplication:\n{mul_result}")
print(f"\nDivision:\n{div_result}")
print(f"\nMatrix Multiplication:\n{matmul_result}")

Addition:
tensor([[ 6,  8],
        [10, 12]])

Subtraction:
tensor([[-4, -4],
        [-4, -4]])

Element-wise Multiplication:
tensor([[ 5, 12],
        [21, 32]])

Division:
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

Matrix Multiplication:
tensor([[19, 22],
        [43, 50]])


In [103]:
"""
torch.mean(input, dim=None, keepdim=False, dtype=None)
torch.mean(input, dim=None, keepdim=False, dtype=None)
"""
tensor = torch.tensor([[1.0, 2.0], 
                       [3.0, 4.0]])
mean_all = torch.mean(tensor)  # Mean of all elements
mean_dim0 = torch.mean(tensor, dim=0)  # Mean along dimension 0 (rows)
mean_dim1 = torch.mean(tensor, dim=1)  # Mean along dimension 1 (columns)

print("Mean of all elements:", mean_all)
print("Mean along dimension 0:", mean_dim0)
print("Mean along dimension 1:", mean_dim1)

# Convert the tensor to `float` type using `.float()` to ensure the mean is computed as a floating-point value
mean_value = a.float().mean() # Calculate the mean of the tensor
print(f"Mean: {mean_value}")

Mean of all elements: tensor(2.5000)
Mean along dimension 0: tensor([2., 3.])
Mean along dimension 1: tensor([1.5000, 3.5000])
Mean: 2.5


In [104]:
"""
torch.std(input, dim=None, unbiased=True, keepdim=False)
unbiased: If True, uses Bessel's correction (divides by n-1 instead of n).
keepdim: Whether to retain the reduced dimension in the output.
"""
x = torch.tensor([[1.0, 2.0], 
                  [3.0, 4.0]])
std_all = torch.std(x)  # Std of all elements
std_dim0 = torch.std(x, dim=0)  # Std along dimension 0 (rows)
std_dim1 = torch.std(x, dim=1)  # Std along dimension 1 (columns)

print("Std of all elements:", std_all)
print("Std along dimension 0:", std_dim0)
print("Std along dimension 1:", std_dim1)

# Convert the tensor to `torch.float32` type using `.type(torch.float32)` to ensure the standard deviation is computed as a floating-point value
std_value = a.type(torch.float32).std() # Calculate the standard deviation of the tensor
print(f"Standard Deviation: {std_value}")

Std of all elements: tensor(1.2910)
Std along dimension 0: tensor([1.4142, 1.4142])
Std along dimension 1: tensor([0.7071, 0.7071])
Standard Deviation: 1.29099440574646


<font color="#00ff21aa" size="4.5" face="Arial"><b>5️⃣ Special Arrays</b></font>

In [25]:
# Create a 2D tensor filled with ones
torch.ones((2, 1))  # The tensor has a shape of (2, 1), meaning it has 2 rows and 1 column

tensor([[1.],
        [1.]])

In [24]:
# Create a 3D tensor filled with zeros
# The tensor has a shape of (3, 4, 3), meaning:
# - 3 matrices (depth/channels)
# - Each matrix has 4 rows and 3 columns
torch.zeros((3, 4, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [27]:
# The tensor has a shape of (5, 4), meaning it has 5 rows and 4 columns
torch.eye(5, 4) # The diagonal elements are set to 1, and all other elements are set to 0

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [28]:
# The tensor has a shape of (4, 3), meaning it has 4 rows and 3 columns
torch.full([4, 3], fill_value=2) # All elements in the tensor are set to the `fill_value` (2 in this case)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

In [25]:
# Create a 2x3 uninitialized tensor
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
"""
torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
start: The starting value of the sequence (default is 0).
end: The ending value of the sequence (exclusive).
step: The step size between values (default is 1).
dtype: The data type of the output tensor (e.g., torch.float32, torch.int64).
requires_grad: If True, the tensor will track operations for automatic differentiation
"""
# Create a tensor with values from 0 to 9
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Create a tensor and reshape it
tensor = torch.arange(6)  # 1D tensor with values 0 to 5
tensor.reshape(2, 3)  # Reshape to 2x3

tensor([[0, 1, 2],
        [3, 4, 5]])

In [30]:
"""
torch.linspace(start, end, steps, *, out=None, dtype=None, device=None, requires_grad=False)
start: The starting value of the sequence.
end: The ending value of the sequence (inclusive).
steps: The number of points in the sequence.
dtype: The data type of the output tensor (e.g., torch.float32, torch.float64).
requires_grad: If True, the tensor will track operations for automatic differentiation.
"""
# Create a tensor with 5 values evenly spaced between 0 and 1
torch.linspace(0, 1, 5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

<font color="#22aa1232" size="4.5" face="Arial"><b>6️⃣ Random Arrays</b></font>

In [101]:
torch.manual_seed(12) # Set a manual seed for reproducibility
torch.rand((4, 3)) # Create a 2D tensor with random values uniformly distributed between 0 and 1 (shape of (4, 3))

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272],
        [0.6373, 0.2421, 0.7312],
        [0.7224, 0.1992, 0.6948]])

In [105]:
torch.manual_seed(12) # Set a manual seed for reproducibility
torch.randn((4, 3)) # Createa 2D tensor filled with random values, uniformly distributed with a mean of 0 and a variance of 1

tensor([[-0.2138, -1.3780, -0.0546],
        [ 0.4515,  0.7858, -1.0884],
        [-0.5599, -0.9336,  0.0479],
        [-0.0844, -0.1471,  0.7590]])

In [ ]:
# Set a manual seed for reproducibility
torch.manual_seed(12)

# Create a 2D tensor with random integer values within a specified range
torch.randint(2, 13, (4, 3)) # The range is from 2 (inclusive) to 13 (exclusive) and a shape of (4, 3)

tensor([[12,  3,  9],
        [11,  2, 10],
        [ 8,  3,  3],
        [10, 11,  2]])

<font color="#22aa1232" size="4.5" face="Arial"><b>6️⃣ Randperm & permute</b></font>

In [98]:
""""""
# Create a random permutation of integers from 0 to 9
torch.randperm(10)

tensor([3, 8, 7, 6, 4, 5, 2, 9, 1, 0])

In [30]:
""""""
# Create a tensor with a specific shape (224, 224, 3) using random values
# This shape is commonly used for RGB images, where:
# - 224 is the height
# - 224 is the width
# - 3 is the number of color channels (Red, Green, Blue)
original = torch.rand(size=(224, 224, 3))

# Permute the tensor to rearrange the order of its axes
# The `permute()` method reorders the dimensions of the tensor
# Here, the new order is (2, 0, 1), which means:
# - The original axis 2 (channels) becomes the new axis 0
# - The original axis 0 (height) becomes the new axis 1
# - The original axis 1 (width) becomes the new axis 2
permuted = original.permute(2, 0, 1)
print(f"Previous shape: {original.shape}")
print(f"New shape: {permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


<font color="#bb1254ff" size="4.5" face="Arial"><b>7️⃣ Indexing & Slicing</b></font>

In [5]:
# Create a 1D tensor with 12 random values from a standard normal distribution (mean=0, std=1)
a = torch.randn(12)
print(f"a: {a}")
print(f"\na[0:1]: {a[0:1]}") # A slice of the tensor containing the first element (as a 1D tensor)
print(f"\na[0]: {a[0]}")     # The first element of the tensor (as a scalar)
print(f"\na[[0, 2, 7]]: {a[[0, 2, 7]]}") # A tensor containing the elements at indices 0, 2, and 7

a: tensor([-0.2834, -0.5340, -0.4740, -0.3780,  1.1992,  0.6316,  0.4599,  1.4253,
        -0.4524,  0.9431,  0.2878, -0.3138])

a[0:1]: tensor([-0.2834])

a[0]: -0.2833613455295563

a[[0, 2, 7]]: tensor([-0.2834, -0.4740,  1.4253])


In [33]:
# `a[2:12:2]`: Slice the tensor from index 2 to index 12 (exclusive) with a step of 2
# `a[2::2]`: Slice the tensor from index 2 to the end with a step of 2
a[2:12:2], a[2::2]

(tensor([ 0.2250,  0.0614, -1.3685,  0.1342, -1.5436]),
 tensor([ 0.2250,  0.0614, -1.3685,  0.1342, -1.5436]))

In [6]:
# Create a 2D tensor with random values from a standard normal distribution (mean=0, std=1)
a = torch.randn(3, 5) # The tensor has a shape of (3, 5), meaning 3 rows and 5 columns
print(f"a:\n{a}")

print(f"\na[0:3, 2:-1]:\n{a[0:3, 2:-1]}") # Slice rows from 0 to 3 (exclusive) and columns from 2 to -1 (exclusive)

print(f"\na[:, 2:-1]:\n{a[:, 2:-1]}") # Slice all rows and columns from 2 to -1 (exclusive)

a:
tensor([[-0.1248, -0.0112,  1.7749,  0.1002,  1.0930],
        [ 0.6211,  0.3059, -0.9071, -1.0935, -0.5858],
        [-1.2401,  0.9980,  0.6931, -1.2044, -0.0793]])

a[0:3, 2:-1]:
tensor([[ 1.7749,  0.1002],
        [-0.9071, -1.0935],
        [ 0.6931, -1.2044]])

a[:, 2:-1]:
tensor([[ 1.7749,  0.1002],
        [-0.9071, -1.0935],
        [ 0.6931, -1.2044]])


In [7]:
print(f"a:\n{a}")
print(f"\na[0:2]:\n{a[0:2]}") # Slice rows from 0 to 2 (exclusive)
print(f"\na[0:2, :]:\n{a[0:2, :]}") # Slice rows from 0 to 2 (exclusive) and all columns

a:
tensor([[-0.1248, -0.0112,  1.7749,  0.1002,  1.0930],
        [ 0.6211,  0.3059, -0.9071, -1.0935, -0.5858],
        [-1.2401,  0.9980,  0.6931, -1.2044, -0.0793]])

a[0:2]:
tensor([[-0.1248, -0.0112,  1.7749,  0.1002,  1.0930],
        [ 0.6211,  0.3059, -0.9071, -1.0935, -0.5858]])

a[0:2, :]:
tensor([[-0.1248, -0.0112,  1.7749,  0.1002,  1.0930],
        [ 0.6211,  0.3059, -0.9071, -1.0935, -0.5858]])


In [8]:
print(f"a:\n{a}")
print(f"\na[::2, 2:]:\n{a[::2, 2:]}") # Slice rows with a step of 2 and columns from index 2 to the end

a:
tensor([[-0.1248, -0.0112,  1.7749,  0.1002,  1.0930],
        [ 0.6211,  0.3059, -0.9071, -1.0935, -0.5858],
        [-1.2401,  0.9980,  0.6931, -1.2044, -0.0793]])

a[::2, 2:]:
tensor([[ 1.7749,  0.1002,  1.0930],
        [ 0.6931, -1.2044, -0.0793]])


In [9]:
# Create a 3D tensor with random values from a standard normal distribution (mean=0, std=1)
# The tensor has a shape of (4, 6, 7), meaning:4 matrices (depth/channels); Each matrix has 6 rows and 7 columns
a = torch.randn(4, 6, 7)
print(f"a shape: {a.shape}")
print(f"\na[1:2, 3:5, 2:4]:\n{a[1:2, 3:5, 2:4]}") # Slice along all three dimensions
print(f"\na[[1], 3:5, 2:4]:\n{a[[1], 3:5, 2:4]}") # Slice using a list for the first dimension
print(f"\na[1, 3:5, 2:4]:\n{a[1, 3:5, 2:4]}") # Slice the first dimension using a single index

a shape: torch.Size([4, 6, 7])

a[1:2, 3:5, 2:4]:
tensor([[[-1.0256, -1.5801],
         [-0.3691, -0.5744]]])

a[[1], 3:5, 2:4]:
tensor([[[-1.0256, -1.5801],
         [-0.3691, -0.5744]]])

a[1, 3:5, 2:4]:
tensor([[-1.0256, -1.5801],
        [-0.3691, -0.5744]])


In [10]:
print(f"a shape: {a.shape}")
print(f"\na[1]:\n{a[1]}") # Select the second matrix (index 1) along the first dimension
print(f"\na[:, :, -1]:\n{a[:, :, -1]}") # Select the last column from all matrices and all rows
print(f"\na[..., -1]:\n{a[..., -1]}") # Same as above, using `...` (ellipsis) to represent all dimensions except the last

a shape: torch.Size([4, 6, 7])

a[1]:
tensor([[ 0.2711,  0.5925, -1.0946, -1.2273, -0.5208,  0.3546, -0.3520],
        [ 1.5682,  0.2059,  0.9340,  2.5062,  0.3773, -0.3898, -0.9249],
        [ 0.5543, -0.5919,  0.4789, -0.1221,  0.0417, -0.3066, -0.2064],
        [-2.1017, -0.1180, -1.0256, -1.5801,  0.4127,  1.2566,  0.2430],
        [ 0.3731, -1.0419, -0.3691, -0.5744, -0.6895, -0.9635,  1.6987],
        [ 0.1723,  0.5141, -0.2876,  0.4528,  0.6898,  0.8877, -0.1313]])

a[:, :, -1]:
tensor([[ 0.5198,  0.6533, -1.0583,  0.4860, -0.6923, -0.4402],
        [-0.3520, -0.9249, -0.2064,  0.2430,  1.6987, -0.1313],
        [ 0.2777, -0.1732,  0.1644,  1.6397,  0.5564,  0.6767],
        [-1.6913,  0.6657,  0.7359, -0.6686,  1.0609,  0.0662]])

a[..., -1]:
tensor([[ 0.5198,  0.6533, -1.0583,  0.4860, -0.6923, -0.4402],
        [-0.3520, -0.9249, -0.2064,  0.2430,  1.6987, -0.1313],
        [ 0.2777, -0.1732,  0.1644,  1.6397,  0.5564,  0.6767],
        [-1.6913,  0.6657,  0.7359, -0.6686,  1

<font color="#aaff5499" size="4.5" face="Arial"><b>8️⃣ Unsqueeze & squeeze</b></font>

In [41]:
"""
torch.squeeze(input, dim=None)
torch.unsqueeze(input, dim)
"""
# Create a tensor with singleton dimensions (dimensions of size 1)
# The tensor has a shape of (1, 3, 1, 4, 1), meaning:
# - 1 matrix (depth/channels)
# - 3 rows
# - 1 column
# - 4 channels
# - 1 additional singleton dimension
tensor_a = torch.randn(1, 3, 1, 4, 1)
print("Original shape of tensor_a:", tensor_a.shape)

# Remove all singleton dimensions using the `squeeze()` method (This eliminates dimensions of size 1)
tensor_b = tensor_a.squeeze()
print("Squeezed shape of tensor_b:", tensor_b.shape)

Original shape of tensor_a: torch.Size([1, 3, 1, 4, 1])
Squeezed shape of tensor_b: torch.Size([3, 4])


In [42]:
# Removing a specific singleton dimension
a = torch.randn(2, 1, 3, 1, 4)
print("Original shape of a:", a.shape)  # Output: torch.Size([2, 1, 3, 1, 4])

# Remove the first dimension (index 0) which is not 1, so no change is done; Output: torch.Size([2, 1, 3, 1, 4])
print(f"{a.squeeze(0).shape = }")

# Remove the second dimension (index 1) which is size 1; Output: torch.Size([2, 3, 1, 4])
print(f"{a.squeeze(1).shape = }")

# Remove the fourth dimension (index 3) which is size 1; Output: torch.Size([2, 1, 3, 4])
print(f"{a.squeeze(3).shape = }")

print(f"{a.squeeze().shape = }")

Original shape of a: torch.Size([2, 1, 3, 1, 4])
a.squeeze(0).shape = torch.Size([2, 1, 3, 1, 4])
a.squeeze(1).shape = torch.Size([2, 3, 1, 4])
a.squeeze(3).shape = torch.Size([2, 1, 3, 4])
a.squeeze().shape = torch.Size([2, 3, 4])


In [11]:
b = torch.randn(2, 2)
print("Original:", b)  # Output: torch.Size([3, 4])

# Add dimension at the beginning (index 0); # Output: torch.Size([1, 3, 4])
print(f"\n{b.unsqueeze(0) = } --> {b.unsqueeze(0).shape = }")
# Add dimension in between the two dimensions (index 1); Output: torch.Size([3, 1, 4])
print(f"\n{b.unsqueeze(1) = } --> {b.unsqueeze(1).shape = }")

# Add dimension at the end (index 2); Output: torch.Size([3, 4, 1])
print(f"\n{b.unsqueeze(2) = } --> {b.unsqueeze(2).shape = }")

Original: tensor([[-2.1785, -0.5201],
        [ 1.0294,  1.8954]])

b.unsqueeze(0) = tensor([[[-2.1785, -0.5201],
         [ 1.0294,  1.8954]]]) --> b.unsqueeze(0).shape = torch.Size([1, 2, 2])

b.unsqueeze(1) = tensor([[[-2.1785, -0.5201]],

        [[ 1.0294,  1.8954]]]) --> b.unsqueeze(1).shape = torch.Size([2, 1, 2])

b.unsqueeze(2) = tensor([[[-2.1785],
         [-0.5201]],

        [[ 1.0294],
         [ 1.8954]]]) --> b.unsqueeze(2).shape = torch.Size([2, 2, 1])


<font color='#hh99gg99' size='4.5' face="Arial"><b>🔟 PyTorch tensors & NumPy</b></font>

In [44]:
array = np.arange(1.0, 8.0) # Create a NumPy array with values ranging from 1.0 to 8.0 (exclusive)
tensor = torch.from_numpy(array) # Convert the NumPy array to a PyTorch tensor
nump = torch.Tensor.numpy(tensor) # Convert the PyTorch tensor back to a NumPy array
print(f"array: {array}")
print(f"tensor: {tensor}")
print(f"nump: {nump}")

array: [1. 2. 3. 4. 5. 6. 7.]
tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
nump: [1. 2. 3. 4. 5. 6. 7.]


**<font color=#e5e90b size='4.5' face="Arial"><b>🔟 Array Manipulation**</b></font><br/>

In [106]:
# ================================================ Stack =======================================================
"""
torch.stack(tensors, dim=0)
torch.cat(tensors, dim=0)
"""
# Create a 2D tensor
a = torch.randn(2, 2)
b = torch.randn(2, 2)
# Stack vertically (along a new dimension)
stacked = torch.stack((a, b), dim=0)
print("Stacked:\n", stacked)

Stacked:
 tensor([[[ 0.1466, -1.0041],
         [-0.7882, -0.8074]],

        [[-0.2957, -0.1462],
         [ 0.3641,  0.4331]]])


In [107]:
# ================================================= Cat ========================================================
# Concatenate horizontally (along an existing dimension)
concatenated = torch.cat((a.unsqueeze(0), b.unsqueeze(0)), dim=1)
print("\nConcatenated:\n", concatenated)


Concatenated:
 tensor([[[ 0.1466, -1.0041],
         [-0.7882, -0.8074],
         [-0.2957, -0.1462],
         [ 0.3641,  0.4331]]])


In [7]:
# =============================================== Split ========================================================
"""
torch.split(tensor, split_size_or_sections, dim=0)
split_size_or_sections:
If an integer, the tensor is split into chunks of size split_size along dim.
If a list of integers, the tensor is split into sections of the specified sizes.
"""
# Create a 2D tensor
a = torch.arange(1, 13).reshape(3, 4)
print(f"\n {a = }")

# Perform horizontal splitting of tensor 'a' into 2 equal parts
print(f"\n {torch.split(a, 2, dim=1) = }")  # horizontal splitting --> 2 means split 2D tensor into 2 equal parts along columns

# Perform vertical splitting of tensor 'a' into 3 equal parts
print(f"\n {torch.split(a, 3, dim=0) = }")  # vertical splitting --> 3 means split 2D tensor into 3 equal parts along rows


 a = tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

 torch.split(a, 2, dim=1) = (tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]), tensor([[ 3,  4],
        [ 7,  8],
        [11, 12]]))

 torch.split(a, 3, dim=0) = (tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),)


In [5]:
# Split a tensor into 2 equal parts
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
split_tensors = torch.split(tensor, 3)
print("Split tensors:", split_tensors)

Split tensors: (tensor([1, 2, 3]), tensor([4, 5, 6]))


In [ ]:
# ========================================== Flatten & ravel ===================================================
"""flattened_tensor = torch.flatten(input, start_dim=0, end_dim=-1)"""
# Create a 3D tensor
a = torch.arange(1, 25).reshape(3, 2, 4)
print(f"\n {a = } , {a.shape = }")

# Flatten the tensor into a 1D tensor
print(f"\n {a.flatten() = }")  # Flatten the tensor into a 1D tensor

'''For `ravel`, since PyTorch doesn't have a `ravel` method, using `view(-1)` or `reshape(-1)` would give a flattened
tensor, Use reshape to achieve ravel-like behavior.'''

print(f"\n {a.reshape(-1) = }")  # Equivalent to ravel in NumPy

# Access the 5th element of the flattened tensor
print(f"\n {a.flatten()[4] = }")  # Access the 5th element of the flattened tensor


 a = tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24]]]) , a.shape = torch.Size([3, 2, 4])

 a.flatten() = tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

 a.reshape(-1) = tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

 a.flatten()[4] = tensor(5)


In [98]:
# Define a 3D tensor with shape (2, 2, 2)
tensor = torch.tensor([[[1, 2], 
                        [3, 4]], 
                          
                       [[5, 6], 
                        [7, 8]]])
print(f"Original tensor:\n{tensor}")

# Flatten the tensor starting from dimension 0 (flattens the entire tensor into a 1D array)
flattened_partial = torch.flatten(tensor, start_dim=0)  
print("\nFullyflattened tensor:", flattened_partial)

# Flatten the tensor starting from dimension 1 (flattens each 2x2 matrix into a 1D array, keeping the outer dimension)
flattened_partial = torch.flatten(tensor, start_dim=1)

# Print the partially flattened tensor (each 2x2 matrix is flattened, but the outer structure remains)
print("\nPartially flattened tensor:\n", flattened_partial)

Original tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

Fullyflattened tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8])

Partially flattened tensor:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [87]:
# ======================================== Clone (copy & deepcopy) =============================================
"""cloned_tensor = tensor.clone()"""
# Create a 2D tensor 
tensor = torch.tensor([[1, 2, 3], 
                       [4, 5, 6]])
print(f"Original tensor:\n{tensor}")

# Clone the tensor
cloned_tensor = tensor.clone()
print(f"\nCloned tensor:\n{cloned_tensor}")

# Modify the cloned tensor
cloned_tensor[0, 0] = 99
print(f"\nModified cloned tensor:\n{cloned_tensor}")
print(f"\nOriginal tensor after modification:\n{tensor}")

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Cloned tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Modified cloned tensor:
tensor([[99,  2,  3],
        [ 4,  5,  6]])

Original tensor after modification:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [12]:
# ================================================ Repeat ======================================================
"""
repeated_tensor = tensor.repeat(*sizes)
*sizes: A sequence of integers specifying how many times to repeat the tensor along each dimension.
"""
# Create a 1D tensor 
tensor = torch.tensor([1, 2, 3])
print(f"Original Tensor: {tensor}")
repeated = tensor.repeat(2)  # Repeat twice along the first (only) dimension
print(f"{tensor.repeat(2) = }")  # Output: tensor([1, 2, 3, 1, 2, 3])

# Create a 2D tensor 
tensor = torch.tensor([[1, 2], 
                       [3, 4]])
print(f"\nOriginal Tensor:\n{tensor}")
repeated = tensor.repeat(2, 3)  # Repeat 2x along rows, 3x along columns
print(f"\nRepeated:\n{tensor.repeat(2, 3)}")

Original Tensor: tensor([1, 2, 3])
tensor.repeat(2) = tensor([1, 2, 3, 1, 2, 3])

Original Tensor:
tensor([[1, 2],
        [3, 4]])

Repeated:
tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])


In [59]:
tensor = torch.tensor([[[1, 2]]])  # Shape: (1, 1, 2)
repeated = tensor.repeat(2, 3, 4)  # Repeat 2x (dim 0), 3x (dim 1), 4x (dim 2)
print(repeated.shape)  # Output: torch.Size([2, 3, 8])
repeated

torch.Size([2, 3, 8])


tensor([[[1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2]],

        [[1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2]]])

In [85]:
# ====================================================== Tile ==================================================
"""tiled_tensor = torch.tile(input, reps)"""
# Create a 1D tensor 
tensor = torch.tensor([1, 2]) 
print(f"Original Tensor: {tensor}")
tiled = torch.tile(tensor, (2,))  # Repeat twice along the first dimension
print(f"{tiled = }")  # Output: tensor([1, 2, 1, 2])

# Create a 2D tensor 
tensor_2d = torch.tensor([[1, 2], 
                          [3, 4]]) 
print(f"\nOriginal Tensor_2d:\n{tensor_2d}")
# Repeat 2x along rows (dim=0) and 3x along columns (dim=1)
tiled = torch.tile(tensor, (2, 3))
print(f"{tiled = }")

tensor = torch.tensor([[[1, 2]]])  # Shape: (1, 1, 2)
print(f"\nOriginal Tensor_3d:\n{tensor}")
tiled = torch.tile(tensor, (2, 3, 4))  # Repeat 2x (dim=0), 3x (dim=1), 4x (dim=2)
print(f"\n{tiled.shape = }")  # Output: torch.Size([2, 3, 8])
tiled

Original Tensor: tensor([1, 2])
tiled = tensor([1, 2, 1, 2])

Original Tensor_2d:
tensor([[1, 2],
        [3, 4]])
tiled = tensor([[1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2]])

Original Tensor_3d:
tensor([[[1, 2]]])

tiled.shape = torch.Size([2, 3, 8])


tensor([[[1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2]],

        [[1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2],
         [1, 2, 1, 2, 1, 2, 1, 2]]])

In [13]:
# ================================================ Unique ======================================================
"""
sorted_tensor, sorted_indices = torch.unique(tensor 
                        sorted=True,          # Return sorted unique values (default: True)
                        return_inverse=False, # Return indices to reconstruct original tensor from unique values
                        return_counts=False,  # Return counts of each unique element
                        dim=None              # Dimension to apply "unique" on (for multi-dimensional tensors)
)
"""
# Create a tensor with duplicate values
tensor = torch.tensor([2, 1, 3, 2, 1])
print(f"Original Tensor: {tensor}")

# Get unique elements and inverse indices
unique_elements, inverse_indices = torch.unique(tensor, return_inverse=True)
print(f"\nunique_elements: {unique_elements}")  # Output: tensor([1, 2, 3])
print(f"\nInverse Indices: {inverse_indices}")  # tensor([1, 0, 2, 1, 0])

# Reconstruct the original tensor from unique values:
reconstructed = unique_elements[inverse_indices]
print(f"\nreconstructed: {reconstructed}")  # Output: tensor([2, 1, 3, 2, 1])

Original Tensor: tensor([2, 1, 3, 2, 1])

unique_elements: tensor([1, 2, 3])

Inverse Indices: tensor([1, 0, 2, 1, 0])

reconstructed: tensor([2, 1, 3, 2, 1])


In [30]:
# Get unique elements and their counts
unique_elements, counts = torch.unique(tensor, return_counts=True)
print("Unique:", unique_elements)    # tensor([1, 2, 3])
print("Counts:", counts)    # tensor([2, 2, 1])

Unique: tensor([1, 2, 3])
Counts: tensor([2, 2, 1])


In [41]:
# Create a 2D tensor with duplicate rows
tensor_2d = torch.tensor([[1, 2], 
                          [3, 4], 
                          [1, 2]])
print(f"Original Tensor:\n {tensor_2d}")

# Find unique rows (dim=0)
unique_rows = torch.unique(tensor_2d, dim=0)
print(f"\nUnique rows:\n{unique_rows}")
# Output: tensor([[1, 2], [3, 4]])

# Find unique columns (dim=1)
tensor_2d_col = torch.tensor([[1, 2, 1], 
                              [3, 4, 3]])
unique_cols = torch.unique(tensor_2d_col, dim=1)
print(f"\nUnique columns:\n{unique_cols}")
# Output: tensor([[1, 2], [3, 4]])

Original Tensor:
 tensor([[1, 2],
        [3, 4],
        [1, 2]])

Unique rows:
tensor([[1, 2],
        [3, 4]])

Unique columns:
tensor([[1, 2],
        [3, 4]])


In [20]:
# ================================================== Sort ======================================================
"""
sorted_tensor, sorted_indices = torch.sort(tensor, 
                                           dim=-1,          # Dimension to sort along (default: last dimension)
                                           descending=False # Sort in ascending (False) or descending (True) order
)
"""
# Create a 1D tensor 
tensor = torch.tensor([3, 1, 4, float('nan'), 2, 5])
print(f"Original Tensor: {tensor}")

sorted_values, sorted_indices = torch.sort(tensor) # PyTorch sorts NaN values to the end by default
print(f"\nSorted values: {sorted_values}")    # tensor([1, 2, 3, 4, 5])
print(f"Sorted indices: {sorted_indices}")    # tensor([1, 3, 0, 2, 4])

# Create a 2D tensor (sort rows)
tensor_2d = torch.tensor([[3, 1], 
                          [4, 2], 
                          [5, 0]])
sorted_rows, row_indices = torch.sort(tensor_2d, dim=1)
print("\nSorted rows:\n", sorted_rows)

# Structured arrays are not directly supported in PyTorch, so we use a list of tuples
# Create a list of tuples with fields 'name', 'height', and 'age'
values = [('A', 1.8, 41), ('R', 1.9, 38), ('Q', 1.7, 38)]

# Sort the list of tuples first by 'height' and then by 'age'
BB = sorted(values, key=lambda x: (x[1], x[2]))
print(f"\nBB('height','age'):\n{BB}")

Original Tensor: tensor([3., 1., 4., nan, 2., 5.])

Sorted values: tensor([1., 2., 3., 4., 5., nan])
Sorted indices: tensor([1, 4, 0, 2, 5, 3])

Sorted rows:
 tensor([[1, 3],
        [2, 4],
        [0, 5]])

BB('height','age'):
[('Q', 1.7, 38), ('A', 1.8, 41), ('R', 1.9, 38)]


In [12]:
# =================================================== Argsort ==================================================
"""
indices = torch.argsort(tensor,
                        dim=-1,          # Dimension to sort along
                        descending=False
)
"""
# Create a 1D tensor 
tensor = torch.tensor([3, 1, 4, 2, 5])
print(f"Original Tensor: {tensor}")

# Get indices to sort a tensor
indices = torch.argsort(tensor, descending=False)
print(f"Argsort indices:{indices}")

# Create a 2D tensor (sort rows)
tensor_2d = torch.tensor([[3, 1], 
                          [4, 2], 
                          [5, 0]])
print(f"\nOriginal Tensor:\n{tensor_2d}")

# Get indices to sort a tensor
indices = torch.argsort(tensor_2d, descending=False)
print(f"\nArgsort indices:\n{indices}")

Original Tensor: tensor([3, 1, 4, 2, 5])
Argsort indices:tensor([1, 3, 0, 2, 4])

Original Tensor:
tensor([[3, 1],
        [4, 2],
        [5, 0]])

Argsort indices:
tensor([[1, 0],
        [1, 0],
        [1, 0]])


In [43]:
# ================================================= Argmax =====================================================
"""
torch.argmax(tensor, 
             dim=None,     # Dimension to reduce (if `None`, returns index of max in flattened tensor)
             keepdim=False # Whether to retain the reduced dimension in the output
)
"""
# Create a 1D tensor 
tensor = torch.tensor([3, 1, 4, 2, 5])
max_idx = torch.argmax(tensor)
print(f"{max_idx = }")  # Output: tensor(4) (index of 5)

# Create a 2D tensor 
tensor_2d = torch.tensor([[3, 1], 
                          [4, 2], 
                          [5, 0]])

# Along rows (dim=0)
max_idx_dim0 = torch.argmax(tensor_2d, dim=0)
print(max_idx_dim0)  # Output: tensor([2, 0]) (indices: [5, 1])

# Along columns (dim=1)
max_idx_dim1 = torch.argmax(tensor_2d, dim=1)
print(max_idx_dim1)  # Output: tensor([0, 0, 0]) (indices: 3, 4, 5)

# Without specifying `dim` (flattens the tensor)
max_idx_flat = torch.argmax(tensor_2d)
print(max_idx_flat)  # Output: tensor(4) (index of 5 in flattened tensor)

max_idx = tensor(4)
tensor([2, 1])
tensor([0, 0, 0])
tensor(4)


In [44]:
# ================================================== Argmin ====================================================
"""
torch.argmin(tensor, 
             dim=None,     # Dimension to reduce
             keepdim=False 
)
"""
# Create a 1D tensor 
tensor_1d = torch.tensor([3, 1, 4, 2, 5])
min_idx_1d = torch.argmin(tensor_1d)
print(min_idx_1d)  # Output: tensor(1) (index of 1)

# Create a 2D tensor 
tensor_2d = torch.tensor([[3, 1], 
                          [4, 2], 
                          [5, 0]])

# Along rows (dim=0)
min_idx_dim0 = torch.argmin(tensor_2d, dim=0)
print(min_idx_dim0)  # Output: tensor([0, 2]) (indices: [3, 0])

# Along columns (dim=1)
min_idx_dim1 = torch.argmin(tensor_2d, dim=1)
print(min_idx_dim1)  # Output: tensor([1, 1, 1]) (indices: 1, 2, 0)

tensor(1)
tensor([0, 2])
tensor([1, 1, 1])


In [66]:
# ====================================== Where, argwhere, & extract ============================================
"""
torch.where(condition, x, y)
torch.nonzero(condition, as_tuple=False)
tensor[condition]
"""
# Create a 2D tensor
tensor = torch.tensor([[1, 2, 3, 4], 
                       [9, 7, 11, -20], 
                       [9, -7, 12, 6]])
print(f"{tensor}")

# If the condition (A >= 3) & (A < 10) is True, keep the original value; otherwise, replace with -10
AA = torch.where((tensor >= 3) & (tensor < 10), tensor, torch.tensor(-10))
print(f"\nA((A>=3) & (A<10), A, -10):\n {AA}")

# torch.argwhere (using torch.nonzero)
indices = torch.nonzero(tensor > 0)  # Find indices of elements > 0
print(f"\ntorch.argwhere:\n{indices}")  

# Extract (using boolean indexing) → tensor[condition]
B = tensor[tensor > 7]
print(f"\n {tensor[tensor > 7] = }")

tensor([[  1,   2,   3,   4],
        [  9,   7,  11, -20],
        [  9,  -7,  12,   6]])

A((A>=3) & (A<10), A, -10):
 tensor([[-10, -10,   3,   4],
        [  9,   7, -10, -10],
        [  9, -10, -10,   6]])

torch.argwhere:
tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 2],
        [2, 3]])

 tensor[tensor > 7] = tensor([ 9, 11,  9, 12])
